### ISSUE TITLE
Transitions, transitions, where are the transitions?

### ISSUE THREAD

**Issue by zipzit** [finn-vgtl/svelte-transitions#3]
README:  

> A growing collection of custom svelte transitions including all default ones provided by svelte.

I'm like, WOW.  Some tooling to help me understand, really understand what's going on with Svelte transitions.    This is going to be so great.  

And then all I get is:  
` return `
        transform: scale(${(1 - percentage) + (percentage * EASE)});
        opacity: ${EASE};
      ``

Please don't get me wrong or color me ungrateful for the effort of your public repo.  I'd just really like to understand each and every aspect of https://svelte.dev/examples#deferred-transitions and in particular
 
- in:receive={{key:image.id}}
- out:send={{key:image.id}}
- {#if selected}  {/if}
- {#await selected then d} {/await} without "unexpected block closing tag"  

sigh..

I'm assuming you set up the readme with great expectations, but haven't quite gotten there yet?  Many thanks for sharing what you have done.

**Comment by finn-vgtl** [comment]
No hard feelings, I totally get where you are coming from.
This package was created for a UI library my team and I are currently working on. Well, two weeks later and the only transition we ever used is that single one which is included in this repo.
So you are totally right about the README being a bit misleading as of now, I’ve just updated it 👍
Sorry this isn’t what you were hoping for.
